name: Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable

      - name: Install Android SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Set up Java environment
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - run: flutter pub cache clean
      - run: flutter pub get
      - run: flutter build apk