name: AutoRelease

on:
  push:
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Write URL
        run: |
          echo "upload_url=${{steps.create_release.outputs.upload_url}}" >> $GITHUB_OUTPUT
  build_web:
    runs-on: macos-latest
    needs: create_release
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.16.5
      - run: flutter pub get
      - run: flutter build web
      - run: flutter build apk
      - name: Package Release
        run: |
          tar -czvf web_release_package.tar.gz ./build/web/*
          tar -czvf apk_release_package.tar.gz ./build/app/outputs/flutter-apk/app-release.apk
          mv web_release_package.tar.gz $GITHUB_WORKSPACE/web_release_package.tar.gz
          mv apk_release_package.tar.gz $GITHUB_WORKSPACE/apk_release_package.tar.gz
      - name: Upload web Release Asset
        env:
          # upload_url: ${{needs.create_release.outputs.upload_url}}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        id: upload-web-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{needs.create_release.outputs.upload_url}}
          asset_path: ${{ github.workspace }}/web_release_package.tar.gz
          asset_name: ros_flutter_gui_app_web.tar.gz
          asset_content_type: application/gzip
      - name: Upload apk Release Asset
        env:
          # upload_url: ${{needs.create_release.outputs.upload_url}}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        id: upload-apk-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{needs.create_release.outputs.upload_url}}
          asset_path: ${{ github.workspace }}/apk_release_package.tar.gz
          asset_name: ros_flutter_gui_app_apk.tar.gz
          asset_content_type: application/gzip
